name = "grove"
version = "0.1.0"
defaultTargets = ["Grove", "print-schema"]

[leanOptions]
experimental.module = true

[[require]]
name = "Cli"
scope = "leanprover"
rev = "nightly-testing"

[[lean_lib]]
name = "Grove"

[[lean_exe]]
name = "print-schema"
root = "PrintSchema"